name: Docker Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script in Docker container
        uses: docker://python:3
        with:
          args: python my_script.py
