name: Docker Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script in Docker container
        id: run_python
        uses: docker://python:3
        with:
          args: sh -c "python script.py 2> error.log || true"

      - name: Send email on failure
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          echo "The Python script failed to execute. Here is the error message:"
          cat error.log | mail -s "GitHub Action - Script Failure" -a "From: $GMAIL_USERNAME" somasaikaushik@gmail.com
