name: Docker Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build the custom Docker image
        run: docker build -t custom-python-image .

      - name: Run Python script in Docker container
        run: docker run --rm custom-python-image python script.py
