name: Python Script Execution

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull python:3.8  # Reference the Python image from Docker Hub

    - name: Run Python script inside Docker container
      id: python-script
      run: docker run python:3.8 python ~/app/my_script.py # Reference the Python image from Docker Hub

    