name: Docker Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the custom Docker image
        run: docker build -t custom-python-image -f test.dockerfile .

      - name: Run Python script in Docker container
        id: run_python
        run: docker run --rm custom-python-image python script.py > output.log || true

      - name: Read output from the log file
        id: read_output
        run: |
          echo "Output from the Python script:"
          cat output.log
          cp output.log send_email_output.log  # Copy the output to another file to use in send_email.py

      - name: Send email on failure or success
        if: always()
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          echo "Sending email with Python script output."
          python send_email.py < send_email_output.log
